basePath: /
definitions:
  main.Product:
    properties:
      id:
        type: integer
      name:
        type: string
      quantity:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a Product API.
  title: Swagger API
  version: "1.0"
paths:
  /product:
    get:
      consumes:
      - application/json
      description: Get details of all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Product'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get all products
      tags:
      - products
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
